// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBJIMey59fZNxzN2H_AfAPGbpQuXpCO-lM',
    appId: '1:301629101974:android:b0b69d46ef7e42108eefb7',
    messagingSenderId: '301629101974',
    projectId: 'lucasgoudin-twitter-clone-app',
    storageBucket: 'lucasgoudin-twitter-clone-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBZknLiHKZu8C2432GD9Ij-WWmprsHW59o',
    appId: '1:301629101974:ios:883b4d4b0c405a6a8eefb7',
    messagingSenderId: '301629101974',
    projectId: 'lucasgoudin-twitter-clone-app',
    storageBucket: 'lucasgoudin-twitter-clone-app.appspot.com',
    iosClientId: '301629101974-av5vlgi7v1gotpsoop3urbde9qa8gaha.apps.googleusercontent.com',
    iosBundleId: 'com.example.twitterClone',
  );
}
